### ISSUE TITLE
GUI showing customers and their orders in the queue = StaffGUI

### ISSUE THREAD

**Issue by aarthi237** [clr3/ASE_Coursework#38]
GUI showing customers and their orders waiting in the queue and details of what each member of serving staff is currently doing.

**Comment by sl1984** [comment]
public ActionListener addButtonActionListener() {
		return new ActionListener() {
	        @Override
	         public void actionPerformed(ActionEvent e) {
	        	new Thread(){
	        	    public void run() {
	        	        try {
	        	        	StaffManager sMgr = new StaffManager(orderManager);
	        	        	sMgr.manageServingStaff();
	        	        } catch (Exception e) {
	        	            e.printStackTrace();
	        	        }

	        	    }}.start();
	        	
	         }
	    };
	}

**Comment by sl1984** [comment]
Above code can be added to the staff gui, on clicking the "Accept new Order" button. This button should be renamed to "Start Staff Simulation".

The Staff provcessing is running in another thread and GUI is not freezing now. However the page is not refreshing to show the latest processing.
